name: Update New arXiv Papers

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * *"
    - cron: "30 2 * * *"

permissions:
  contents: write  # This grants write access to the repository contents
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if you have any in a requirements.txt file)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update new listings
        env:
          TZ: America/Chicago  # Set your desired timezone here
        run: |
          python fetch.py > output.txt  
          echo "# KICP/A&A astro-ph listing" > README.md  # Add your static content
          echo "" >> README.md
          echo "## Latest Astro-ph Papers (Generated on $(date))" >> README.md
          echo "" >> README.md
          cat output.txt >> README.md

      # Step 6: Commit and push the updated README.md
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "[action] astro-ph auto update"
          git push
